### ISSUE TITLE
Crash with Latest Version on Fabric 1.21.1

### ISSUE THREAD

**Issue by rrwatson** [Benjamin-Norton/AllTheTrims#50]
Hey there,
Looks like this is causing crashing on MC 1.21.1 Fabric Loader 0.16.7. Crash log is below. SS of mods used provided
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'configurable' at 'com.bawnorton.configurable.platform.ConfigurableMainWrapper'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.UnsupportedOperationException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.toFile(ZipPath.java:673)
	at knot//com.bawnorton.configurable.ConfigurableMain.lambda$init$3(ConfigurableMain.java:54)
	at knot//com.bawnorton.configurable.platform.Platform.lambda$forEachJar$0(Platform.java:28)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at knot//com.bawnorton.configurable.platform.Platform.forEachJar(Platform.java:25)
	at knot//com.bawnorton.configurable.ConfigurableMain.init(ConfigurableMain.java:52)
	at knot//com.bawnorton.configurable.platform.ConfigurableMainWrapper.onInitialize(ConfigurableMainWrapper.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
![image](https://github.com/user-attachments/assets/a5ef6858-deee-4b38-8b89-905dc97d5de7)

**Comment by Bawnorton** [comment]
Should be fixed in configurable 2.1.2
